// Common or dashboard
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_SIDEBAR_OPEN = "SET_IS_SIDEBAR_OPEN";

//Review
export const GET_ASTROLOGERS_REVIEWS = "GET_ASTROLOGERS_REVIEWS";
export const SET_ASTROLOGERS_REVIEWS = "SET_ASTROLOGERS_REVIEWS";
export const GET_APP_REVIEWS = "GET_APP_REVIEWS";
export const SET_APP_REVIEWS = "SET_APP_REVIEWS";
export const UPDATE_ASTROLOER_REVIEW_STATUS = "UPDATE_ASTROLOER_REVIEW_STATUS";
export const DELETE_ASTROLOGER_REVIEW = "DELETE_ASTROLOGER_REVIEW";

//Customer
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const SET_ALL_CUSTOMER = "SET_ALL_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const BAN_CUSTOMER = "BAN_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

//Astrologer
export const GET_ALL_ASTROLOGER = "GET_ALL_ASTROLOGER";
export const GET_ASTROLOGER = "GET_ASTROLOGER";
export const SET_ALL_ASTROLOGER = "SET_ALL_ASTROLOGER";
export const UPDATE_ASTROLOGER_CHAT_STATUS = "UPDATE_ASTROLOGER_CHAT_STATUS";
export const UPDATE_ASTROLOER_CALL_STATUS = "UPDATE_ASTROLOER_CALL_STATUS";
export const GET_ENQUIRY_ASTROLOGERS = "GET_ENQUIRY_ASTROLOGERS";
export const SET_ENQUIRY_ASTROLOGERS = "SET_ENQUIRY_ASTROLOGERS";
export const UPDATE_ENQUIRY_STATUS = "UPDATE_ENQUIRY_STATUS";
export const UPDATE_ASTROLOGER_DATA = "UPDATE_ASTROLOGER_DATA";
export const UPDATE_ASTROLOGER_STATUS = "UPDATE_ASTROLOGER_STATUS";
// export const UPDATE_ASTROLOGER_CALL_STATUS = "UPDATE_ASTROLOGER_CALL_STATUS";
export const ADD_ASTROLOGER = "ADD_ASTROLOGER";
export const VERIFY_UNVERIFY_ASTROLOGER = "VERIFY_UNVERIFY_ASTROLOGER";
export const DELETE_ASTROLOGER = "DELETE_ASTROLOGER";

//Experties
export const GET_ALL_EXPERTIES = "GET_ALL_EXPERTIES";
export const GET_ALL_ACTIVE_EXPERTIES = "GET_ALL_ACTIVE_EXPERTIES";
export const GET_ALL_MAIN_EXPERTIES = "GET_ALL_MAIN_EXPERTIES";
export const SET_ALL_EXPERTIES = "SET_ALL_EXPERTIES";
export const SET_ALL_MAIN_EXPERTIES = "SET_ALL_MAIN_EXPERTIES";
export const CREATE_EXPERTIES = "CREATE_EXPERTIES";
export const CREATE_MAIN_EXPERTIES = "CREATE_MAIN_EXPERTIES";
export const UPDATE_EXPERTIES = "UPDATE_EXPERTIES";
export const UPDATE_MAIN_EXPERTIES = "UPDATE_MAIN_EXPERTIES";
export const DELETE_EXPERTIES = "DELETE_EXPERTIES";
export const DELETE_MAIN_EXPERTIES = "DELETE_MAIN_EXPERTIES";
export const UPDATE_EXPERTISE_STATUS = "UPDATE_EXPERTISE_STATUS";


//Skills
export const CREATE_SKILL = "CREATE_SKILL";
export const GET_ALL_SKILLS = "GET_ALL_SKILLS";
export const GET_ALL_ACTIVE_SKILLS = "GET_ALL_ACTIVE_SKILLS";
export const SET_ALL_SKILLS = "SET_ALL_SKILLS";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_SKILL_STATUS = "UPDATE_SKILL_STATUS";

export const CREATE_SUB_SKILL = "CREATE_SUB_SKILL";
export const GET_ALL_SUB_SKILLS = "GET_ALL_SUB_SKILLS";
export const SET_ALL_SUB_SKILLS = "SET_ALL_SUB_SKILLS";
export const UPDATE_SUB_SKILL = "UPDATE_SUB_SKILL";
export const DELETE_SUB_SKILL = "DELETE_SUB_SKILL";
export const UPDATE_SUB_SKILL_STATUS = "UPDATE_SUB_SKILL_STATUS";

//Remedies
export const CREATE_REMEDY = "CREATE_REMEDY";
export const GET_ALL_REMEDIES = "GET_ALL_REMEDIES";
export const GET_ALL_ACTIVE_REMEDIES = "GET_ALL_ACTIVE_REMEDIES";
export const SET_ALL_REMEDIES = "SET_ALL_REMEDIES";
export const UPDATE_REMEDY = "UPDATE_REMEDY";
export const DELETE_REMEDY = "DELETE_REMEDY";
export const CHANGE_REMEDY_STATUS = "CHANGE_REMEDY_STATUS"

//Redirection Banners
export const CREATE_REDIRECTION_BANNER = 'CREATE_REDIRECTION_BANNER'
export const GET_REDIRECTION_BANNER = 'GET_REDIRECTION_BANNER'
export const SET_REDIRECTION_BANNER = 'SET_REDIRECTION_BANNER'
export const UPDATE_REDIRECTION_BANNER = 'UPDATE_REDIRECTION_BANNER'
export const DELETE_REDIRECTION_BANNER = 'DELETE_REDIRECTION_BANNER'
export const CHANGE_REDIRECTION_BANNER_STATUS = 'CHANGE_REDIRECTION_BANNER_STATUS'

//Course
export const GET_ALL_COURSES = 'GET_ALL_COURSES'
export const CREATE_COURSE = 'CREATE_COURSE'

//Course Banner
export const GET_ALL_COURSE_BANNER = 'GET_ALL_COURSE_BANNER'
export const CREATE_COURSE_BANNER = 'CREATE_COURSE_BANNER'
export const UPDATE_COURSE_BANNER = 'UPDATE_COURSE_BANNER'
export const UPDATE_COURSE_BANNER_STATUS = 'UPDATE_COURSE_BANNER_STATUS'
export const DELETE_COURSE_BANNER = 'DELETE_COURSE_BANNER'

//Ecommerce Banner
export const GET_ALL_ECOMMERCE_BANNER = 'GET_ALL_ECOMMERCE_BANNER'
export const CREATE_ECOMMERCE_BANNER = 'CREATE_ECOMMERCE_BANNER'
export const UPDATE_ECOMMERCE_BANNER = 'UPDATE_ECOMMERCE_BANNER'
export const UPDATE_ECOMMERCE_BANNER_STATUS = 'UPDATE_ECOMMERCE_BANNER_STATUS'
export const DELETE_ECOMMERCE_BANNER = 'DELETE_ECOMMERCE_BANNER'

//Product Banner
export const GET_ALL_PRODUCT_BANNER = 'GET_ALL_PRODUCT_BANNER'
export const CREATE_PRODUCT_BANNER = 'CREATE_PRODUCT_BANNER'
export const UPDATE_PRODUCT_BANNER = 'UPDATE_PRODUCT_BANNER'
export const UPDATE_PRODUCT_BANNER_STATUS = 'UPDATE_PRODUCT_BANNER_STATUS'
export const DELETE_PRODUCT_BANNER = 'DELETE_PRODUCT_BANNER'

//Pooja Banner
export const GET_ALL_POOJA_BANNER = 'GET_ALL_POOJA_BANNER'
export const CREATE_POOJA_BANNER = 'CREATE_POOJA_BANNER'
export const UPDATE_POOJA_BANNER = 'UPDATE_POOJA_BANNER'
export const UPDATE_POOJA_BANNER_STATUS = 'UPDATE_POOJA_BANNER_STATUS'
export const DELETE_POOJA_BANNER = 'DELETE_POOJA_BANNER'

//Call-Chat Banner
export const GET_ALL_CALL_CHAT_BANNER = 'GET_ALL_CALL_CHAT_BANNER'
export const CREATE_CALL_CHAT_BANNER = 'CREATE_CALL_CHAT_BANNER'
export const UPDATE_CALL_CHAT_BANNER = 'UPDATE_CALL_CHAT_BANNER'
export const UPDATE_CALL_CHAT_BANNER_STATUS = 'UPDATE_CALL_CHAT_BANNER_STATUS'
export const DELETE_CALL_CHAT_BANNER = 'DELETE_CALL_CHAT_BANNER'


//Notification
export const GET_CUSTOMER_NOTIFICATIONS = "GET_CUSTOMER_NOTIFICATIONS";
export const GET_ASTROLOGER_NOTIFICATIONS = "GET_ASTROLOGER_NOTIFICATIONS";
export const SET_CUSTOMER_NOTIFICATIONS = "GET_CUSTOMER_NOTIFICATIONS";
export const SET_ASTROLOGER_NOTIFICATIONS = "GET_ASTROLOGER_NOTIFICATIONS";
export const SEND_CUSTOMER_NOTIFICATIONS = "SEND_CUSTOMER_NOTIFICATIONS";
export const SEND_ASTROLOGER_NOTIFICATIONS = "SEND_ASTROLOGER_NOTIFICATIONS";
export const DELETE_CUSTOMER_NOTIFICATIONS = "GET_CUSTOMER_NOTIFICATIONS";
export const DELETE_ASTROLOGER_NOTIFICATIONS = "GET_ASTROLOGER_NOTIFICATIONS";

//History
export const GET_CHAT_HISTORY = "GET_CHAT_HISTORY";
export const SET_CHAT_HISTORY = "SET_CHAT_HISTORY";
export const GET_CHAT_SUMMARY = "GET_CHAT_SUMMARY";
export const SET_CHAT_SUMMARY = "SET_CHAT_SUMMARY";
export const GET_CALL_HISTORY = "GET_CALL_HISTORY";
export const SET_CALL_HISTORY = "SET_CALL_HISTORY";
export const SET_CUSTOMER_FIREBASE_ID = 'SET_CUSTOMER_FIREBASE_ID'

//Dashboard
export const GET_DASHBOARD = "GET_DASHBOARD";
export const SET_DASHBOARD = "SET_DASHBOARD";

//Reports
export const GET_ADMIN_EARNINGS = "GET_ADMIN_EARNINGS";
export const SET_ADMIN_EARNINGS = "SET_ADMIN_EARNINGS";
export const GET_RECIEPT_SUMMARY = 'GET_RECIEPT_SUMMARY'
export const SET_RECIEPT_SUMMARY = 'SET_RECIEPT_SUMMARY'

//Language
export const CREATE_LANGUAGE = "CREATE_LANGUAGE";
export const GET_ALL_LANGUAGE = "GET_ALL_LANGUAGE";
export const SET_ALL_LANGUAGE = "SET_ALL_LANGUAGE";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";

//Country
export const GET_ALL_COUNTRY = "GET_ALL_COUNTRY";
export const SET_ALL_COUNTRY = "SET_ALL_COUNTRY";
export const UPDATE_COUNTRY_STATUS = "UPDATE_COUNTRY_STATUS";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY" ;
export const COUNTRY_STATE_LIST = "COUNTRY_STATE_LIST";

//State
export const GET_ALL_STATE = "GET_ALL_STATE";
export const UPDATE_STATE_STATUS = "UPDATE_STATE_STATUS";
export const UPDATE_STATE = "UPDATE_STATE";
export const CREATE_STATE = "CREATE_STATE";
export const DELETE_STATE = "DELETE_STATE" 

//City
export const GET_ALL_CITY = "GET_ALL_CITY";
export const UPDATE_CITY_STATUS = "UPDATE_CITY_STATUS";
export const UPDATE_CITY = "UPDATE_CITY";
export const CREATE_CITY = "CREATE_CITY";
export const DELETE_CITY = "DELETE_CITY" 
export const STATE_CITY_LIST = "STATE_CITY_LIST";


//Recharge Plan

export const CREATE_RECHARGE_PLAN = 'CREATE_RECHARGE_PLAN';
export const GET_RECHARGE_PLAN = 'GET_RECHARGE_PLAN'
export const SET_RECHARGE_PLAN = 'SET_RECHARGE_PLAN'
export const UPDATE_RECHARGE_PLAN = 'UPDATE_RECHARGE_PLAN'
export const DELETE_RECHARGE_PLAN = 'DELETE_RECHARGE_PLAN'
export const UPDATE_RECHARGE_PLAN_STATUS = 'UPDATE_RECHARGE_PLAN_STATUS'

//FirstRecharge Offer
export const CREATE_FIRST_RECHARGE_OFFER = 'CREATE_FIRST_RECHARGE_OFFER'
export const GET_FIRST_RECHARGE_OFFER = 'GET_FIRST_RECHARGE_OFFER'
export const SET_FIRST_RECHARGE_OFFER = 'SET_FIRST_RECHARGE_OFFER'
export const UPDATE_FIRST_RECHARGE_OFFER = 'UPDATE_FIRST_RECHARGE_OFFER'
export const UPDATE_FIRST_RECHARGE_OFFER_STATUS = 'UPDATE_FIRST_RECHARGE_OFFER_STATUS'
export const DELETE_FIRST_RECHARGE_OFFER = 'DELETE_FIRST_RECHARGE_OFFER'

//Product Category
export const CREATE_PRODUCT_CATEGORY = 'CREATE_PRODUCT_CATEGORY'
export const PRODUCT_CATEGORY_LIST = 'PRODUCT_CATEGORY_LIST'
export const UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY'
export const DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY'
export const UPDATE_PRODUCT_CATEGORY_STATUS = 'UPDATE_PRODUCT_CATEGORY_STATUS'

//Product 
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const PRODUCT_LIST = 'PRODUCT_LIST'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const UPDATE_PRODUCT_STATUS = 'UPDATE_PRODUCT_STATUS'

//Pooja Category
export const CREATE_POOJA_CATEGORY = 'CREATE_POOJA_CATEGORY'
export const POOJA_CATEGORY_LIST = 'POOJA_CATEGORY_LIST'
export const UPDATE_POOJA_CATEGORY = 'UPDATE_POOJA_CATEGORY'
export const DELETE_POOJA_CATEGORY = 'DELETE_POOJA_CATEGORY'
export const UPDATE_POOJA_CATEGORY_STATUS = 'UPDATE_POOJA_CATEGORY_STATUS'
export const UPDATE_POOJA_CATEGORY_IMAGE = 'UPDATE_POOJA_CATEGORY_IMAGE'
export const CREATE_POOJA_CATEGORY_SUCCESS = 'CREATE_POOJA_CATEGORY_SUCCESS';
export const CREATE_POOJA_CATEGORY_FAILURE = 'CREATE_POOJA_CATEGORY_FAILURE';
export const POOJA_CATEGORY_LIST_SUCCESS= 'POOJA_CATEGORY_LIST_SUCCESS'
export const POOJA_CATEGORY_LIST_FAILURE = 'POOJA_CATEGORY_LIST_FAILURE'

//Pooja
export const CREATE_POOJA = 'CREATE_POOJA'
export const POOJA_LIST = 'POOJA_LIST'
export const UPDATE_POOJA = 'UPDATE_POOJA'
export const DELETE_POOJA = 'DELETE_POOJA'
export const UPDATE_POOJA_STATUS = 'UPDATE_POOJA_STATUS'

//BLOG  CATEGORY
export const CREATE_BLOG_CATEGORY='CREATE_BLOG_CATEGORY'
export const BLOG_CATEGORY_LIST='BLOG_CATEGORY_LIST'
export const UPDATE_BLOG_CATEGORY='UPDATE_BLOG_CATEGORY'
export const DELETE_BLOG_CATEGORY='DELETE_BLOG_CATEGORY'
export const ACTIVE_BLOG_CATEGORY='ACTIVE_BLOG_CATEGORY'


//BLOG
export const CREATE_BLOG='CREATE_BLOG'
export const BLOG_LIST='BLOG_LIST'
export const UPDATE_BLOG='UPDATE_BLOG'
export const DELETE_BLOG='DELETE_BLOG'
export const DELETE_MULTIPLE_BLOG='DELETE_MULTIPLE_BLOG'

//TESTIMONIAL
export const CREATE_TESTIMONIAL='CREATE_TESTIMONIAL'
export const TESTIMONIAL_LIST='TESTIMONIAL_LIST'
export const UPDATE_TESTIMONIAL='UPDATE_TESTIMONIAL'
export const DELETE_TESTIMONIAL='DELETE_TESTIMONIAL'
export const UPDATE_TESTIMONIAL_STATUS = 'UPDATE_TESTIMONIAL_STATUS'







